root: true

parserOptions:
  sourceType: module
  ecmaVersion: 2021

env:
  browser: true
  node: true
  es2021: true

extends:
  - eslint:recommended
  - prettier

plugins:
  - svelte3

overrides:
  - files:
      - '*.svelte'
    processor: svelte3/svelte3

rules:
  no-unused-vars:
    - error
    - argsIgnorePattern: ^_
