extends:
  - stylelint-config-standard
  - stylelint-config-sass-guidelines
  - stylelint-config-prettier

rules:
  selector-pseudo-class-no-unknown:
    - true
    - ignorePseudoClasses: [global]

  rule-empty-line-before: always

  max-nesting-depth: null

  selector-max-compound-selectors: null

  selector-no-qualifying-type: null
